# fgw 配置文件
# 启动方式：cd fgw/bin && ../../build/fgw/fgw
# 节：[log] [db] [api] [fdm]

[log]
# 日志路径
path = ./log
# 日志级别
level = 1
# 单位M , 0 -同步写文件
que_size = 0

[db]
# 数据库源
source = fgw_dsn
# 数据库账户
user = fgw_user
# 数据库账户密码
passwd = fgw_pass
# 数据库链接异常重连间隔
reconnect_interval = 300
# data_engine 加载周期（秒，默认 10）
load_interval = 10
# db 线程绑定的cpu
cpu_id = -1

[api]
# api 监听ip
listen_ip = 0.0.0.0
# api 监听端口
listen_port = 18888
# 心跳间隔，默认 5s
heart_interval = 5
# 单位M
que_size = 16
# api 引擎线程数（= 发送队列数）
thread_num = 4
# 绑定的cpu, 若设置，应与数量一致
thread_cpus = 1,2,3,4

[fdm]
# 心跳间隔，默认 5s
heart_interval = 5
# 单位M
que_size = 32
# fdm 引擎线程数（= 发送队列数）
thread_num = 4
# 绑定的cpu, 若设置，应与数量一致
thread_cpus = 5,6,7,8
